### ISSUE TITLE
I love your Think Style blog post.

### ISSUE THREAD

**Issue by hdngo** [egarreau/egarreau.github.io#1]
And I want to say thank you, on behalf of all the other Bumblebees.

But seriously, Evangeline, I really felt like I was in your shoes as I read your post, and that's something I haven't come experienced yet while reading other blogs. Yours was totally personable and refreshing on a whole nother level. You went through some crazy anxiety I'm sure, but for you to feel comfortable with taking a step back to start again and come out on top is something that a lot of us newcomers can come to appreciate. I know that a lot of us are worried about having to repeat, deal with financial issues, compete with other job hunters, etc., but I really think that you found your calm before the storm. Don't know if I used that correctly...anyways. Great post. I'd definitely like to pair with ya before Phase 0 is over since you're in the Chicago cohort!

And with that, welcome to the Bumblebees cohort! :)

**Comment by egarreau** [comment]
Harvey,

Thank you so much for your kind words! I can't tell you how much I appreciate your warm welcome to the cohort. Hope to pair with you soon!
